
# Task Logic For Starting Sample
execute as @a[tag=inspect_sample,tag=blue] at @e[tag=blue_inspect_sample] if score Medbay-InspectSample Tasks_Blue matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=blue] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=red] at @e[tag=red_inspect_sample] if score Medbay-InspectSample Tasks_Red matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=red] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=yellow] at @e[tag=yellow_inspect_sample] if score Medbay-InspectSample Tasks_Yellow matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=yellow] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=orange] at @e[tag=orange_inspect_sample] if score Medbay-InspectSample Tasks_Orange matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=orange] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=black] at @e[tag=black_inspect_sample] if score Medbay-InspectSample Tasks_Black matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=black] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=white] at @e[tag=white_inspect_sample] if score Medbay-InspectSample Tasks_White matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=white] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=cyan] at @e[tag=cyan_inspect_sample] if score Medbay-InspectSample Tasks_Cyan matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=cyan] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=purple] at @e[tag=purple_inspect_sample] if score Medbay-InspectSample Tasks_Purple matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=purple] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=pink] at @e[tag=pink_inspect_sample] if score Medbay-InspectSample Tasks_Pink matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=pink] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=brown] at @e[tag=brown_inspect_sample] if score Medbay-InspectSample Tasks_Brown matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=brown] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=green] at @e[tag=green_inspect_sample] if score Medbay-InspectSample Tasks_Green matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=green] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=lime] at @e[tag=lime_inspect_sample] if score Medbay-InspectSample Tasks_Lime matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=lime] run scoreboard players set @s in_task 0

execute as @a[tag=inspect_sample,tag=blue] at @e[tag=blue_inspect_sample] if score Medbay-InspectSample Tasks_Blue matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Blue 59
execute as @a[tag=inspect_sample,tag=red] at @e[tag=red_inspect_sample] if score Medbay-InspectSample Tasks_Red matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Red 59
execute as @a[tag=inspect_sample,tag=yellow] at @e[tag=yellow_inspect_sample] if score Medbay-InspectSample Tasks_Yellow matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Yellow 59
execute as @a[tag=inspect_sample,tag=orange] at @e[tag=orange_inspect_sample] if score Medbay-InspectSample Tasks_Orange matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Orange 59
execute as @a[tag=inspect_sample,tag=black] at @e[tag=black_inspect_sample] if score Medbay-InspectSample Tasks_Black matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Black 59
execute as @a[tag=inspect_sample,tag=white] at @e[tag=white_inspect_sample] if score Medbay-InspectSample Tasks_White matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_White 59
execute as @a[tag=inspect_sample,tag=cyan] at @e[tag=cyan_inspect_sample] if score Medbay-InspectSample Tasks_Cyan matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Cyan 59
execute as @a[tag=inspect_sample,tag=purple] at @e[tag=purple_inspect_sample] if score Medbay-InspectSample Tasks_Purple matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Purple 59
execute as @a[tag=inspect_sample,tag=pink] at @e[tag=pink_inspect_sample] if score Medbay-InspectSample Tasks_Pink matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Pink 59
execute as @a[tag=inspect_sample,tag=brown] at @e[tag=brown_inspect_sample] if score Medbay-InspectSample Tasks_Brown matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Brown 59
execute as @a[tag=inspect_sample,tag=green] at @e[tag=green_inspect_sample] if score Medbay-InspectSample Tasks_Green matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Green 59
execute as @a[tag=inspect_sample,tag=lime] at @e[tag=lime_inspect_sample] if score Medbay-InspectSample Tasks_Lime matches 60 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run scoreboard players set Medbay-InspectSample Tasks_Lime 59

execute as @a[tag=inspect_sample,tag=blue] at @e[tag=blue_inspect_sample] if score Medbay-InspectSample Tasks_Blue matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=red] at @e[tag=red_inspect_sample] if score Medbay-InspectSample Tasks_Red matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=yellow] at @e[tag=yellow_inspect_sample] if score Medbay-InspectSample Tasks_Yellow matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=orange] at @e[tag=orange_inspect_sample] if score Medbay-InspectSample Tasks_Orange matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=black] at @e[tag=black_inspect_sample] if score Medbay-InspectSample Tasks_Black matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=white] at @e[tag=white_inspect_sample] if score Medbay-InspectSample Tasks_White matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=cyan] at @e[tag=cyan_inspect_sample] if score Medbay-InspectSample Tasks_Cyan matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=purple] at @e[tag=purple_inspect_sample] if score Medbay-InspectSample Tasks_Purple matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=pink] at @e[tag=pink_inspect_sample] if score Medbay-InspectSample Tasks_Pink matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=brown] at @e[tag=brown_inspect_sample] if score Medbay-InspectSample Tasks_Brown matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=green] at @e[tag=green_inspect_sample] if score Medbay-InspectSample Tasks_Green matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=lime] at @e[tag=lime_inspect_sample] if score Medbay-InspectSample Tasks_Lime matches 59 if block ~5 ~-1 ~5 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear

# Countdown Timer
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Blue > @a[tag=inspect_sample,tag=blue,limit=1] zero if score Medbay-InspectSample Tasks_Blue < @a[tag=inspect_sample,tag=blue,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Blue 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Red > @a[tag=inspect_sample,tag=red,limit=1] zero if score Medbay-InspectSample Tasks_Red < @a[tag=inspect_sample,tag=red,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Red 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Yellow > @a[tag=inspect_sample,tag=yellow,limit=1] zero if score Medbay-InspectSample Tasks_Yellow < @a[tag=inspect_sample,tag=yellow,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Yellow 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Orange > @a[tag=inspect_sample,tag=orange,limit=1] zero if score Medbay-InspectSample Tasks_Orange < @a[tag=inspect_sample,tag=orange,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Orange 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Black > @a[tag=inspect_sample,tag=black,limit=1] zero if score Medbay-InspectSample Tasks_Black < @a[tag=inspect_sample,tag=black,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Black 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_White > @a[tag=inspect_sample,tag=white,limit=1] zero if score Medbay-InspectSample Tasks_White < @a[tag=inspect_sample,tag=white,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_White 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Cyan > @a[tag=inspect_sample,tag=cyan,limit=1] zero if score Medbay-InspectSample Tasks_Cyan < @a[tag=inspect_sample,tag=cyan,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Cyan 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Purple > @a[tag=inspect_sample,tag=purple,limit=1] zero if score Medbay-InspectSample Tasks_Purple < @a[tag=inspect_sample,tag=purple,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Purple 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Pink > @a[tag=inspect_sample,tag=pink,limit=1] zero if score Medbay-InspectSample Tasks_Pink < @a[tag=inspect_sample,tag=pink,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Pink 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Brown > @a[tag=inspect_sample,tag=brown,limit=1] zero if score Medbay-InspectSample Tasks_Brown < @a[tag=inspect_sample,tag=brown,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Brown 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Green > @a[tag=inspect_sample,tag=green,limit=1] zero if score Medbay-InspectSample Tasks_Green < @a[tag=inspect_sample,tag=green,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Green 1
execute as @a[scores={global_delay=5},limit=1] if score Medbay-InspectSample Tasks_Lime > @a[tag=inspect_sample,tag=lime,limit=1] zero if score Medbay-InspectSample Tasks_Lime < @a[tag=inspect_sample,tag=lime,limit=1] sixty run scoreboard players remove Medbay-InspectSample Tasks_Lime 1

# Show Anomally
execute as @a[tag=inspect_sample,limit=1] run function au:tasks/inspect_sample_randomize

# Task Logic For Checking Sample
execute as @a[tag=inspect_sample,tag=blue] at @e[tag=blue_inspect_sample] if score Medbay-InspectSample Tasks_Blue matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=blue] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=red] at @e[tag=red_inspect_sample] if score Medbay-InspectSample Tasks_Red matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=red] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=yellow] at @e[tag=yellow_inspect_sample] if score Medbay-InspectSample Tasks_Yellow matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=yellow] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=orange] at @e[tag=orange_inspect_sample] if score Medbay-InspectSample Tasks_Orange matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=orange] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=black] at @e[tag=black_inspect_sample] if score Medbay-InspectSample Tasks_Black matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=black] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=white] at @e[tag=white_inspect_sample] if score Medbay-InspectSample Tasks_White matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=white] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=cyan] at @e[tag=cyan_inspect_sample] if score Medbay-InspectSample Tasks_Cyan matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=cyan] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=purple] at @e[tag=purple_inspect_sample] if score Medbay-InspectSample Tasks_Purple matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=purple] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=pink] at @e[tag=pink_inspect_sample] if score Medbay-InspectSample Tasks_Pink matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=pink] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=brown] at @e[tag=brown_inspect_sample] if score Medbay-InspectSample Tasks_Brown matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=brown] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=green] at @e[tag=green_inspect_sample] if score Medbay-InspectSample Tasks_Green matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=green] run scoreboard players set @s in_task 0
execute as @a[tag=inspect_sample,tag=lime] at @e[tag=lime_inspect_sample] if score Medbay-InspectSample Tasks_Lime matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] at @e[type=minecraft:armor_stand,tag=lime] run scoreboard players set @s in_task 0

execute as @a[tag=inspect_sample,tag=blue] at @e[tag=blue_inspect_sample] if score Medbay-InspectSample Tasks_Blue matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=red] at @e[tag=red_inspect_sample] if score Medbay-InspectSample Tasks_Red matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=yellow] at @e[tag=yellow_inspect_sample] if score Medbay-InspectSample Tasks_Yellow matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=orange] at @e[tag=orange_inspect_sample] if score Medbay-InspectSample Tasks_Orange matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=black] at @e[tag=black_inspect_sample] if score Medbay-InspectSample Tasks_Black matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=white] at @e[tag=white_inspect_sample] if score Medbay-InspectSample Tasks_White matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=cyan] at @e[tag=cyan_inspect_sample] if score Medbay-InspectSample Tasks_Cyan matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=purple] at @e[tag=purple_inspect_sample] if score Medbay-InspectSample Tasks_Purple matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=pink] at @e[tag=pink_inspect_sample] if score Medbay-InspectSample Tasks_Pink matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=brown] at @e[tag=brown_inspect_sample] if score Medbay-InspectSample Tasks_Brown matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=green] at @e[tag=green_inspect_sample] if score Medbay-InspectSample Tasks_Green matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear
execute as @a[tag=inspect_sample,tag=lime] at @e[tag=lime_inspect_sample] if score Medbay-InspectSample Tasks_Lime matches 0 if block ~5 ~-1 ~10 minecraft:redstone_lamp[lit=true] run function au:tasks/inspect_sample_clear