
# Set Pet Select in Computer
replaceitem block 93 67 -88 container.26 minecraft:milk_bucket{display:{Name:'[{"text":"Clear Pet","color":"white","bold":true},{"text":"","color":"white","bold":false}]'}} 1
replaceitem block 93 67 -88 container.7 minecraft:feather{display:{Name:'[{"text":"Mini Crewmate","color":"blue","bold":true},{"text":"","color":"blue","bold":false}]'}} 1
replaceitem block 93 67 -88 container.8 minecraft:wither_rose{display:{Name:'[{"text":"Turtle","color":"blue","bold":true},{"text":"","color":"blue","bold":false}]'}} 1

# Tell when someone chooses a pet
tag @a[nbt={Inventory:[{id:"minecraft:wither_rose"}]}] add get_pet
tag @a[nbt={Inventory:[{id:"minecraft:wither_rose"}]}] add turtle
tag @a[nbt={Inventory:[{id:"minecraft:feather"}]}] add get_pet
tag @a[nbt={Inventory:[{id:"minecraft:feather"}]}] add drsus
tag @a[nbt={Inventory:[{id:"minecraft:milk_bucket"}]}] add remove_pet

# Remove Pet
execute as @a[tag=remove_pet,tag=brown] run kill @e[tag=pet_brown,tag=pet]
execute as @a[tag=remove_pet,tag=lime] run kill @e[tag=pet_lime,tag=pet]
execute as @a[tag=remove_pet,tag=green] run kill @e[tag=pet_green,tag=pet]
execute as @a[tag=remove_pet,tag=yellow] run kill @e[tag=pet_yellow,tag=pet]
execute as @a[tag=remove_pet,tag=orange] run kill @e[tag=pet_orange,tag=pet]
execute as @a[tag=remove_pet,tag=red] run kill @e[tag=pet_red,tag=pet]
execute as @a[tag=remove_pet,tag=blue] run kill @e[tag=pet_blue,tag=pet]
execute as @a[tag=remove_pet,tag=white] run kill @e[tag=pet_white,tag=pet]
execute as @a[tag=remove_pet,tag=black] run kill @e[tag=pet_black,tag=pet]
execute as @a[tag=remove_pet,tag=cyan] run kill @e[tag=pet_cyan,tag=pet]
execute as @a[tag=remove_pet,tag=pink] run kill @e[tag=pet_pink,tag=pet]
execute as @a[tag=remove_pet,tag=purple] run kill @e[tag=pet_purple,tag=pet]

# Kill Previous Pets
execute as @a[tag=get_pet,tag=brown] run kill @e[tag=pet_brown,tag=pet]
execute as @a[tag=get_pet,tag=lime] run kill @e[tag=pet_lime,tag=pet]
execute as @a[tag=get_pet,tag=green] run kill @e[tag=pet_green,tag=pet]
execute as @a[tag=get_pet,tag=yellow] run kill @e[tag=pet_yellow,tag=pet]
execute as @a[tag=get_pet,tag=orange] run kill @e[tag=pet_orange,tag=pet]
execute as @a[tag=get_pet,tag=red] run kill @e[tag=pet_red,tag=pet]
execute as @a[tag=get_pet,tag=blue] run kill @e[tag=pet_blue,tag=pet]
execute as @a[tag=get_pet,tag=white] run kill @e[tag=pet_white,tag=pet]
execute as @a[tag=get_pet,tag=black] run kill @e[tag=pet_black,tag=pet]
execute as @a[tag=get_pet,tag=cyan] run kill @e[tag=pet_cyan,tag=pet]
execute as @a[tag=get_pet,tag=pink] run kill @e[tag=pet_pink,tag=pet]
execute as @a[tag=get_pet,tag=purple] run kill @e[tag=pet_purple,tag=pet]

# Kill previous pets when switch color
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:red_dye"}]} run kill @e[tag=pet_red]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:orange_dye"}]} run kill @e[tag=pet_orange]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:yellow_dye"}]} run kill @e[tag=pet_yellow]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:lime_dye"}]} run kill @e[tag=pet_lime]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:green_dye"}]} run kill @e[tag=pet_green]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:cyan_dye"}]} run kill @e[tag=pet_cyan]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:blue_dye"}]} run kill @e[tag=pet_blue]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:pink_dye"}]} run kill @e[tag=pet_pink]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:purple_dye"}]} run kill @e[tag=pet_purple]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:white_dye"}]} run kill @e[tag=pet_white]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:brown_dye"}]} run kill @e[tag=pet_brown]
execute if block 93 67 -88 minecraft:barrel{Items:[{id:"minecraft:black_dye"}]} run kill @e[tag=pet_black]

### Summon Pet ###

# Turtle
execute at @a[tag=brown] as @a[tag=brown,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_brown","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=lime] as @a[tag=lime,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_lime","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=green] as @a[tag=green,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_green","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=yellow] as @a[tag=yellow,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_yellow","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=orange] as @a[tag=orange,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_orange","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=pink] as @a[tag=pink,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_pink","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=white] as @a[tag=white,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_white","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=black] as @a[tag=black,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_black","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=cyan] as @a[tag=cyan,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_cyan","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=blue] as @a[tag=blue,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_blue","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=red] as @a[tag=red,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_red","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=purple] as @a[tag=purple,tag=get_pet,tag=turtle] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:wither_rose", tag:{CustomModelData:713}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_purple","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}

# Dr. Sus
execute at @a[tag=red] as @a[tag=red,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:1}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_red","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=orange] as @a[tag=orange,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:2}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_orange","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=yellow] as @a[tag=yellow,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:3}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_yellow","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=lime] as @a[tag=lime,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:5}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_lime","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=green] as @a[tag=green,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:4}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_green","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=cyan] as @a[tag=cyan,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:6}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_cyan","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=blue] as @a[tag=blue,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:7}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_blue","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=white] as @a[tag=white,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:10}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_white","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=pink] as @a[tag=pink,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:9}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_pink","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=black] as @a[tag=black,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:11}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_black","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=brown] as @a[tag=brown,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:12}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_brown","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}
execute at @a[tag=purple] as @a[tag=purple,tag=get_pet,tag=drsus] run summon minecraft:armor_stand ~ ~-1.5 ~ {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 20.0d, Name: "generic.maxHealth"}, {Base: 0.0d, Name: "generic.knockbackResistance"}, {Base: 0.699999988079071d, Name: "generic.movementSpeed"}, {Base: 0.0d, Name: "generic.armor"}, {Base: 0.0d, Name: "generic.armorToughness"}], Invulnerable: 0b, FallFlying: 0b, ShowArms: 1b, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, DisabledSlots: 0, DeathTime: 0s, Pose: {RightArm: [-90.0f, 0.0f, 0.0f], LeftLeg: [0.0f, 0.0f, 0.0f], Head: [0.0f, 0.001f, 0.0f], LeftArm: [0.0f, 0.0f, 0.0f], RightLeg: [0.0f, 0.0f, 0.0f], Body: [0.0f, 0.001f, 0.0f]}, Invisible: 0b, Tags: ["as_modified"], Motion: [0.0d, 0.0d, 0.0d], Small: 0b, Health: 20.0f, Air: 300s, OnGround: 1b, Rotation: [0f, 0.0f], HandItems: [{id: "minecraft:feather", tag:{CustomModelData:8}, Count: 1b}, {}], Fire: -1s, ArmorItems: [{}, {}, {}, {}], NoBasePlate: 0b, HurtTime: 0s,Invisible:1b,Tags:["pet_purple","pet","as_sealed","as_locked","Stand"],DisabledSlots:2096896}

# Cleanup
# UNCOMMENT THIS LINE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
clear @a wither_rose
clear @a feather
clear @a milk_bucket
tag @a[tag=get_pet] remove turtle
tag @a[tag=get_pet] remove drsus
tag @a[tag=get_pet] remove get_pet
tag @a[tag=remove_pet] remove remove_pet
