
execute as @a[tag=purple,scores={RNG=0}] if score Common_Tasks Settings matches 1.. run scoreboard players set Navigation-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Common_Tasks Settings matches 1.. run scoreboard players set Admin-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Long_Tasks Settings matches 1.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Long_Tasks Settings matches 2.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Long_Tasks Settings matches 3.. run scoreboard players set Navigation-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Long_Tasks Settings matches 4.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Long_Tasks Settings matches 5.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 1.. run scoreboard players set O2-EmptyChute Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 2.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 3.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 4.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 5.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 6.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 7.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 8.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 9.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=0}] if score Short_Tasks Settings matches 10.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=1}] if score Common_Tasks Settings matches 1.. run scoreboard players set Electrical-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Common_Tasks Settings matches 1.. run scoreboard players set Security-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Common_Tasks Settings matches 1.. run scoreboard players set Admin-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Long_Tasks Settings matches 1.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Long_Tasks Settings matches 2.. run scoreboard players set Cafeteria-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Long_Tasks Settings matches 3.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Long_Tasks Settings matches 4.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Long_Tasks Settings matches 5.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 1.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 2.. run scoreboard players set Cafeteria-EmptyGarbage Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 3.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 4.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 5.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 6.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 7.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 8.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 9.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=1}] if score Short_Tasks Settings matches 10.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=2}] if score Common_Tasks Settings matches 1.. run scoreboard players set Navigation-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Common_Tasks Settings matches 1.. run scoreboard players set Security-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Common_Tasks Settings matches 1.. run scoreboard players set Electrical-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Long_Tasks Settings matches 1.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Long_Tasks Settings matches 2.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Long_Tasks Settings matches 3.. run scoreboard players set Communications-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Long_Tasks Settings matches 4.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Long_Tasks Settings matches 5.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 1.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 2.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 3.. run scoreboard players set O2-EmptyChute Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 4.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 5.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 6.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 7.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 8.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 9.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=2}] if score Short_Tasks Settings matches 10.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=3}] if score Common_Tasks Settings matches 1.. run scoreboard players set Electrical-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Common_Tasks Settings matches 1.. run scoreboard players set Admin-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Long_Tasks Settings matches 1.. run scoreboard players set Weapons-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Long_Tasks Settings matches 2.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Long_Tasks Settings matches 3.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Long_Tasks Settings matches 4.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Long_Tasks Settings matches 5.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 1.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 2.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 3.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 4.. run scoreboard players set Cafeteria-EmptyGarbage Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 5.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 6.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 7.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 8.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 9.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=3}] if score Short_Tasks Settings matches 10.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=4}] if score Common_Tasks Settings matches 1.. run scoreboard players set Navigation-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Common_Tasks Settings matches 1.. run scoreboard players set Electrical-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Long_Tasks Settings matches 1.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Long_Tasks Settings matches 2.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Long_Tasks Settings matches 3.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Long_Tasks Settings matches 4.. run scoreboard players set Electrical-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Long_Tasks Settings matches 5.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 1.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 2.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 3.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 4.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 5.. run scoreboard players set O2-EmptyChute Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 6.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 7.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 8.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 9.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=4}] if score Short_Tasks Settings matches 10.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=5}] if score Common_Tasks Settings matches 1.. run scoreboard players set Navigation-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Common_Tasks Settings matches 1.. run scoreboard players set Admin-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Common_Tasks Settings matches 1.. run scoreboard players set Security-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Long_Tasks Settings matches 1.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Long_Tasks Settings matches 2.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Long_Tasks Settings matches 3.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Long_Tasks Settings matches 4.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Long_Tasks Settings matches 5.. run scoreboard players set Navigation-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 1.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 2.. run scoreboard players set Navigation-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 3.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 4.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 5.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 6.. run scoreboard players set Cafeteria-EmptyGarbage Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 7.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 8.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 9.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=5}] if score Short_Tasks Settings matches 10.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=6}] if score Common_Tasks Settings matches 1.. run scoreboard players set Navigation-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Common_Tasks Settings matches 1.. run scoreboard players set Security-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Long_Tasks Settings matches 1.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Long_Tasks Settings matches 2.. run scoreboard players set Cafeteria-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Long_Tasks Settings matches 3.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Long_Tasks Settings matches 4.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Long_Tasks Settings matches 5.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 1.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 2.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 3.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 4.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 5.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 6.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 7.. run scoreboard players set O2-EmptyChute Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 8.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 9.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=6}] if score Short_Tasks Settings matches 10.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=7}] if score Common_Tasks Settings matches 1.. run scoreboard players set Admin-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Common_Tasks Settings matches 1.. run scoreboard players set Electrical-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Long_Tasks Settings matches 1.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Long_Tasks Settings matches 2.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Long_Tasks Settings matches 3.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Long_Tasks Settings matches 4.. run scoreboard players set Electrical-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Long_Tasks Settings matches 5.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 1.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 2.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 3.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 4.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 5.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 6.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 7.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 8.. run scoreboard players set Cafeteria-EmptyGarbage Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 9.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=7}] if score Short_Tasks Settings matches 10.. run scoreboard players set O2-CleanFilter Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=8}] if score Common_Tasks Settings matches 1.. run scoreboard players set Navigation-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Common_Tasks Settings matches 1.. run scoreboard players set Electrical-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Long_Tasks Settings matches 1.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Long_Tasks Settings matches 2.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Long_Tasks Settings matches 3.. run scoreboard players set Weapons-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Long_Tasks Settings matches 4.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Long_Tasks Settings matches 5.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 1.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 2.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 3.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 4.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 5.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 6.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 7.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 8.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 9.. run scoreboard players set O2-EmptyChute Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=8}] if score Short_Tasks Settings matches 10.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1

execute as @a[tag=purple,scores={RNG=9}] if score Common_Tasks Settings matches 1.. run scoreboard players set Admin-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Common_Tasks Settings matches 1.. run scoreboard players set Storage-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Common_Tasks Settings matches 1.. run scoreboard players set Security-Wires Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Common_Tasks Settings matches 2.. run scoreboard players set Admin-Cardswipe Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Long_Tasks Settings matches 1.. run scoreboard players set Storage-GetGas Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Long_Tasks Settings matches 2.. run scoreboard players set Communications-Download Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Long_Tasks Settings matches 3.. run scoreboard players set Medbay-InspectSample Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Long_Tasks Settings matches 4.. run scoreboard players set Reactor-StartReactor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Long_Tasks Settings matches 5.. run scoreboard players set Medbay-SubmitScan Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 1.. run scoreboard players set Weapons-ClearAsteroids Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 2.. run scoreboard players set UpperEngine-AlignEngine Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 3.. run scoreboard players set Navigation-ChartCourse Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 4.. run scoreboard players set Shields-PrimeShields Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 5.. run scoreboard players set Electrical-DivertPower Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 6.. run scoreboard players set O2-CleanFilter Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 7.. run scoreboard players set Electrical-CalibrateDistributor Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 8.. run scoreboard players set Navigation-StabilizeSteering Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 9.. run scoreboard players set Reactor-ManifestFolds Tasks_Purple 1
execute as @a[tag=purple,scores={RNG=9}] if score Short_Tasks Settings matches 10.. run scoreboard players set Cafeteria-EmptyGarbage Tasks_Purple 1

